<html>
<head>
  <style>
  
        <?php
		  if (isset($css_styles))
			{
			echo $css_styles;
			}
      ?>

	@page {
	  margin-top: 130px;
	  margin-bottom: 30px;
	  margin-right: 30px;
	  margin-left: 30px;
	}	

	#header { position: fixed; left: 0px; top: -110px; right: 0px; height: 110px;  text-align: center; }
    #footer { position: fixed; left: 0px; bottom: -10px; right: 0px; height: 250px;  }
    #footer .page:after { content: counter(page, upper-roman); }
  </style>
     <-- 
	 Change only the bottom hight to insert more signatures
	 #header { position: fixed; left: 0px; top: -480px; right: 0px; height: 480px; background-color: orange; text-align: center; }
    #footer { position: fixed; left: 0px; bottom: -170px; right: 0px; height: 170px; background-color: lightblue; }
    #footer .page:after { content: counter(page, upper-roman); }
	-->
<body>
    <?php

    $company_name = Yii::app()->params['companyName'];
    $address = Yii::app()->params['Address'];
    $tel = Yii::app()->params['Tel'];
    $fax = Yii::app()->params['Fax']; 
    $username = Yii::app()->getModule("user")->user()->username;
    $date = date("F j, Y, g:i a");
    ?>
  <div id="header">
          <table>
            <tr>
                <td style="padding-right: 20px"><img src="./images/NationalSymbol.jpg" height="70px" width="70px" style="margin-top: -20px;float: left;"/></td>
				<td style = 'border-left: 2px solid black'>
                    <table>
                        <tr >
                            <td style="font-size: 16px; align:left"  >
                                <?php echo "<b>" .  trim($company_name) . "</b>, " . trim($address); ?>
                            </td>
                            
                        </tr>
                        <tr>
                            <td style="font-size: 16px">
                                <?php echo  trim($tel); ?>
								<?php if(isset($vat_no)){?>
                                 <?php echo trim($fax); ?>
								<?php }?>
                            <?php if(isset($vat_no) && trim($vat_no) != ""  ){?>
                                 VAT No: <?php echo trim($vat_no);?>
                            </td>
                        </tr>
							<?php }?>
                        
                    </table> 
				</td>
            </tr>
        </table>
        <hr/>	
    <?php  echo "<div style='font-size: 18px; align:center; padding-top: 10px;  padding-right: 10px; padding-bottom: 10px;  padding-left: 10px;' ><b>" . $page_header . "</b></div>" ;?>
  </div>
  <div id="footer">
    <?php echo $page_footer;?>
        <div style="position: fixed;bottom:-1;left:0"><img src="./images/report_footer_logo.png" height="25px" width="50px" ></div> 
        <hr style = "position:fixed;bottom:0;left:0;width:92%"/>
        <div style = "position:fixed;bottom:-2;left:160"><span style = "font-size:12px;"><?php echo "Report generated by " . $username . " on " . $date; ?></span></div>
		<?php if(isset($doc_no) && isset($issue_no) && isset($issue_date))
        { ?>
              <table style = "font-size:12px; position:fixed;bottom:12;left:10;width:100%">
                    <tr>
                        <!--<th>Doc. No: <?php echo $doc_no; ?></th>
                        <th>Doc. Rev. No: <?php echo $issue_no; ?></th>
                        <th>Doc. Effective Date: <?php echo $issue_date; ?></th>-->
                    </tr>
                </table>

        <?php }?>     
        <div  style="position: fixed;bottom:-5;left:520" class="page1"></div>
  </div>
  <div id="content">
	<?php echo $page_content;?>
  </div>
</body>
</html>

