<?php

class DriverPerformanceForm extends CFormModel
{

//public $Valid_From,$Valid_To;
	public $Valid_From;
	public $Valid_To;
	public $Vehicle_Status_ID;

	public function rules()
	{
		return array(
			array('Valid_From, Valid_To', 'required')
			
		);
	}
	
	 public function attributeLabels()
    {
        return array(
			'Valid_From'=>'From Date',	
			'Valid_To'=>'To Date'		
		);
	}
	
	
	/*public function combodata($var)
	{
		
		if($var == 'DS')
		{
		   $values=	Yii::app()->db->createCommand()
                   ->select('DS_Division_ID, DS_Division_Name')
                   ->from('ma_ds_divisions')
					   /* ->join('tbl_profile p', 'u.id=p.user_id')
						->where('id=:id', array(':id'=>$id)) */ 
				   //->queryAll();
   			
		//}
		//elseif($var == 'GN')
		//{
		   	//$values=Yii::app()->db->createCommand()
                   //->select('GN_Division_ID, GN_Division_Name')
                   //->from('ma_gn_divisions')
                   //->queryAll();
				  
		//}
		//elseif($var == 'Member')
		//{
		   	//$values=Yii::app()->db->createCommand()
                   //->select('Member_ID, Name_with_Initials')
                   //->from('personal_details')
                   //->queryAll();
				  
		//}
		
		//return($values);
	//}*/
	
   public function rprint($vFromDate, $vToDate)
	{
		$DataSource = new ReportDataSource;
		require_once('./protected/class/class.ezpdf.php');
		$pdf = new Cezpdf();
        $pdf->selectFont('./protected/class/fonts/Courier.afm');
		
		
		//echo $Vehicle_No." - ".$vFromDate." - ".$vToDate, exit;
	
		
		$mystr=$DataSource->ArrayFuelDriverPerformance($vFromDate, $vToDate);
		//$mystrSummary=$DataSource->ArrayFuelConsumptionbyVehicleInSummary($vFromDate, $vToDate);
		$ArrCount = count($mystr);	
		
		
		 $Top=600;
		 $Right=330;
		 $LeftFront=32;
		 $LeftBack=150;
				
	
		 $pdf->ezText(Yii::app()->params['companyName'],14);
	
		 
		//$pdf->ezText('Local Governance Program',15);
		 $pdf->ezText('',2);
		 //$pdf->ezText('Fleet Management System',14);		
		 $pdf->ezText(Yii::app()->params['sysName'],12);
		 $pdf->ezText('',5);
		//$pdf->ezText('Driver Performance Summary Report - (From: '.$vFromDate.' To: '.$vToDate.')',12);
		 $pdf->ezText('Driver Performance Summary Report',10);
		 $pdf->ezText('',5);
		 //$pdf->ezText('All Drivers',12);
		 $pdf->ezText('From: '.$vFromDate.' To: '.$vToDate,10);
		 $pdf->ezText('',28);		
		 $pdf->addJpegFromFile("./images/NationalSymbol.jpg",'500','740','71','87');
		 //$pdf->addText(400,730,8,"<i>''Towards Next Generation Government''</i>",0);
		
		 //--add Line to report
		$pdf->line(560,723,30,723);
		$pdf->line(560,724.5,30,724.5);
		 
		  //$Top=$Top+100;
		 
		 $Top = 750;
		 if ($ArrCount > 0) 
		//print_r($mystr); exit;
		{
		 $pdf->ezTable($mystr,'','',array('xPos'=>'right','xOrientation'=>'left','width'=>540));
		 //$pdf->ezText('',15);
		 //$pdf->ezText('<b>Summary details in total</b>',12);
		 //$pdf->ezText('',10);
		 //$pdf->ezTable($mystrSummary,'','',array('xPos'=>'right','xOrientation'=>'left','width'=>540));
		 	 
		 }
		else
		{
			$pdf->ezText('* No data available for selected criteria',10);
			$pdf->ezStream();
		}
		 //$pdf->addJpegFromFile("./images/FC1.jpg",'40','550','500','150');

			$pdf->line(580,20,15,20);
			 $pdf->addText(420,10,8,"Generated by- ".Yii::app()->getModule('user')->user()->username);			
			$Time = date("Y/m/d");
			$pdf->addText(540,10,8,$Time,0);					
			$pdf->ezStartPageNumbers(60,10,8);					
			//---Footer End here----
				
			$pdf->ezStream();					
		
	
	
	}
}

?>
