<?php

class FuelConsumptionAllVehicleDateForm extends CFormModel
{

//public $Valid_From,$Valid_To;
	public $Valid_From;
	public $Valid_To;
	public $Vehicle_Status_ID;

	public function rules()
	{
		return array(
			array('Valid_From, Valid_To', 'required')
			
		);
	}
	
	 public function attributeLabels()
    {
        return array(
			'Valid_From'=>'From Date',	
			'Valid_To'=>'To Date'		
		);
	}

   public function rprint($vFromDate, $vToDate)
	{
		$DataSource = new ReportDataSource;
		require_once('./protected/class/class.ezpdf.php');
		$pdf = new Cezpdf();
        $pdf->selectFont('./protected/class/fonts/Courier.afm');
		
		
		//echo $Vehicle_No." - ".$vFromDate." - ".$vToDate, exit;
	
		
		$mystr=$DataSource->ArrayFuelConsumptionbyVehicleAll($vFromDate, $vToDate);
		//$mystrSummary=$DataSource->ArrayFuelConsumptionbyVehicleInSummary($vFromDate, $vToDate);
		$ArrCount = count($mystr);	
		
		
		 $Top=600;
		 $Right=330;
		 $LeftFront=32;
		 $LeftBack=150;
				
	
		 $pdf->ezText(Yii::app()->params['companyName'],14);
	
		 
		//$pdf->ezText('Local Governance Program',15);
		 $pdf->ezText('',2);
		 //$pdf->ezText('Fleet Management System',14);		
		 $pdf->ezText(Yii::app()->params['sysName'],12);
		 $pdf->ezText('',5);
		 $pdf->ezText('Fuel Consumption Summary Report - (From: '.$vFromDate.' To: '.$vToDate.')',10);
		 $pdf->ezText('',5);
		 $pdf->ezText('All Vehicles',10);
		 $pdf->ezText('',28);		
		 $pdf->addJpegFromFile("./images/NationalSymbol.jpg",'500','740','71','87');
		 //$pdf->addText(400,730,8,"<i>''Towards Next Generation Government''</i>",0);
		
		 //--add Line to report
		 $pdf->line(560,723,30,723);
                 $pdf->line(560,724.5,30,724.5);
		 $pdf->ezText('',5);
		  //$Top=$Top+100;
		 
		 $Top = 750;
		 if ($ArrCount > 0) 
		//print_r($mystr); exit;
		{
		 $pdf->ezTable($mystr,'','',
		 array('cols' => array('Vehicle No.' => array('width'=>'100'), 'Volumn(L)     (a)' => array('width'=>'100'), 'Amount(Rs)      (b)' => array('justification' => 'right', 'width'=>'120'), 'Distance Driven(km)        (d)' => array('width'=>'100'), 'Liters per 100km(L/100km)    (a*100)/d' => array('width'=>'120'))));
		}
		else
		{
			$pdf->ezText('* No data available for selected criteria',10);
			$pdf->ezStream();
		}
		 //$pdf->ezText('',15);
		 //$pdf->ezText('<b>Summary details in total</b>',12);
		 //$pdf->ezText('',10);
		 //$pdf->ezTable($mystrSummary,'','',array('xPos'=>'right','xOrientation'=>'left','width'=>540));
		 	 
		 
		 //$pdf->addJpegFromFile("./images/FC1.jpg",'40','550','500','150');

			$pdf->line(580,20,15,20);
			 $pdf->addText(420,10,8,"Generated by- ".Yii::app()->getModule('user')->user()->username);			
			$Time = date("Y/m/d");
			$pdf->addText(540,10,8,$Time,0);					
			$pdf->ezStartPageNumbers(60,10,8);					
			//---Footer End here----
				
			$pdf->ezStream();					
		
	
	
	}
}

?>
