<?php

class InsuranceForm extends CFormModel
{

    public $Vehicle_Category_ID;
    public $Valid_From;
    public $Valid_To;
	


	
    public function rules()
    {
        return array(
            array('Valid_To, Valid_From, Vehicle_Category_ID','required')
        );
    }
	
    public function attributeLabels()
    {
        return array(
            'Vehicle_Category_ID' => 'Vehicle Category ID',
            'Valid_From' => 'From Date',
            'Valid_To' => 'To Date',				
        );                      
               
    }
	
	
    public function rprint($vFromDate,$vToDate,$vCategory)
    {
        $DataSource = new ReportDataSource;
        require_once('./protected/class/class.ezpdf.php');
        $pdf = new Cezpdf();
        $pdf->selectFont('./protected/class/fonts/Courier.afm');

        //--Get data array 		
        $mystr=$DataSource->Arrayinsurance($vFromDate,$vToDate,$vCategory);		
        $ArrCount = count($mystr);	

        //--add Heddings
        $pdf->ezText(Yii::app()->params['companyName'],14);

        $cri = new CDbCriteria();
        $cri->select="Category_Name";
        $cri->condition="Vehicle_Category_ID=$vCategory";

        $vcat = VehicleCategory::model()->findAll($cri);
        if(count($vcat)>0)
        {
            $category = $vcat[0]['Category_Name'];
        }

        $pdf->ezText('',2);
        $pdf->ezText(Yii::app()->params['sysName'],12);
        $pdf->ezText('',5);
        $pdf->ezText('Vehicle Insuarance Due Report-From:'.$vFromDate.' To:'.$vToDate,9);
        $pdf->ezText('',5);		
        $pdf->ezText('Vehicle Category - '.$category,9);
        $pdf->ezText('',28);		
        $pdf->addJpegFromFile("./images/NationalSymbol.jpg",'500','740','71','87');
       //$pdf->addText(400,730,8,"<i>'Towards Next Generation Government'</i>",0);		

        //--add Line to report
        $pdf->line(560,723,20,723);
        $pdf->line(560,724.5,20,724.5);	
         $pdf->ezText('',5);	
		 		 
		 $Top=690;
		 $Right=330;
		 $LeftFront=32;
		 $LeftBack=150;
		 		
		if ($ArrCount > 0)  // $ArrCount start
		{
		 $pdf->ezTable($mystr,array('Vehicle_No'=>'Vehicle No.','Date_of_Insurance'=>'Date of Insurance','Insurance_Company_Name'=>'Insurance Company','Insurance_Type'=>'Insurance Type','Amount'=>'Amount','Sum_Insured'=>'Sum Insured','Valid_To'=>'Expire Date'),'', 
		 array('cols' => array('Vehicle_No' => array('width'=>'77'), 'Date_of_Insurance' => array('width'=>'65'), 'Insurance_Company_Name' => array('width'=>'120'), 'Insurance_Type' => array('width'=>'77'), 'Amount' => array('justification' => 'right', 'width'=>'77'), 'Sum_Insured' => array('justification' => 'right', 'width'=>'77'))));
		}
		else
		{
			$pdf->ezText('* No data available for selected criteria',10);
			$pdf->ezStream();
		}
		 
		 
		 
		 
		 $pdf->setColor(0.0,0.0,0.0);
		
			//--add Line to report (Page footer)---
			$pdf->line(580,20,15,20);
			$pdf->addText(420,10,8,"Generated by- ".Yii::app()->getModule('user')->user()->username);			
			$Time = date("Y/m/d");
			$pdf->addText(540,10,8,$Time,0);					
			$pdf->ezStartPageNumbers(60,10,8);					
			//---Footer End here----
				
			$pdf->ezStream();					
		
	}	
}

?>
