<?php

class UserwiseBookingForm extends CFormModel {

    public $Valid_From;
    public $Valid_To;
    public $User_ID;

    public function rules()
    {
        return array(
            array('Valid_From, Valid_To,User_ID', 'required')

        );

    }

    public function attributeLabels()
    {
        return array(
            'Valid_From' => 'From Date',
            'Valid_To' => 'To Date',
            'User_ID' => 'Requester',
        );
    }

    public function rprint($Valid_From, $Valid_To,$requester){

        $DataSource = new ReportDataSource;
        require_once('./protected/class/class.ezpdf.php');
        $pdf = new Cezpdf();
        $pdf->Cezpdf($paper='A4',$orientation='landscape');
      	$pdf->selectFont('./protected/class/fonts/Courier.afm');
      
        $mystr=$DataSource->ArrayUserwiseBooking($Valid_From,$Valid_To, $requester);
        $ArrCount = count($mystr);

        $requestedBy ='';

        $usr = new CDbCriteria;
        $usr->select = "username";
        $usr->condition = "id='$requester'";


        $usrArr = Yii::app()->getModule('user')->user()->findAll($usr);
        if(count($usrArr)>0)
        {
            $requestedBy = $usrArr[0]['username'];
        }
        $pdf->ezText(Yii::app()->params['companyName'],14);


        $pdf->ezText('',2);

        $pdf->ezText(Yii::app()->params['sysName'],12);
        $pdf->ezText('',5);
        $pdf->ezText('Vehicle Bookings From - '.$Valid_From.' To '.$Valid_To,12);
        $pdf->ezText('by- '.$requestedBy,12);
        $pdf->ezText('',28);
      	$pdf->addJpegFromFile("./images/NationalSymbol.jpg",'700','490','71','87');
		//$pdf->addText(650,480,8,"<i>'Towards Next Generation Government'</i>",0);		
		
        $pdf->ezText('',5);
        //--add Line to report
        $pdf->line(800,460,30,460);
		 $pdf->line(800,462,30,462);
                 $pdf->ezText('',20);

        $tbwith=780;
        $Top=690;
        $Right=330;
        $LeftFront=32;
        $LeftBack=150;

        if($ArrCount > 0)
        {
            $pdf->ezTable($mystr,array('Vehicle_No'=>'Vehicle No.', 'Category_Name'=>'Category', 'Full_Name'=>'Driver', 'From'=>'From', 'To'=>'To', 'Place_from'=>'Place From', 'Place_to'=>'Place To','Description'=>'Reason', 'username'=>'Requested by',),'',array('xPos'=>'right','xOrientation'=>'left','width'=> $tbwith));
        }
        else
        {
            $pdf->ezText('* No data available for selected criteria',10);
            $pdf->ezStream();
        }
        $pdf->setColor(0.0,0.0,0.0);

        //--add Line to report (Page footer)---
        $pdf->line(820,20,15,20);
        $pdf->addText(420,10,8,"Generated by- ".Yii::app()->getModule('user')->user()->username);
        $Time = date("Y/m/d");
        $pdf->addText(540,10,8,$Time,0);
        $pdf->ezStartPageNumbers(60,10,8);
        //---Footer End here----

        $pdf->ezStream();

    }

}
?>
