<?php

class vehicleRepaireServiceDateForm extends CFormModel
{

//public $Valid_From,$Valid_To;
	public $Valid_From;
	public $Valid_To;
	public $Vehicle_Status_ID;

	public function rules()
	{
		return array(
			array('Valid_From, Valid_To', 'required')
			
		);
	}
	
	 public function attributeLabels()
    {
        return array(
			'Valid_From'=>'From Date',	
			'Valid_To'=>'To Date'		
		);
	}
	
	
	
	
    public function rprint($Vehicle_No, $vFromDate, $vToDate)
    {
        $DataSource = new ReportDataSource;
        require_once('./protected/class/class.ezpdf.php');
        $pdf = new Cezpdf();
        $pdf->Cezpdf($paper='A4',$orientation='landscape');
      	$pdf->selectFont('./protected/class/fonts/Courier.afm');
			  
        //--Get data array 
        $mystrR=$DataSource->ArrayVehicleRepaire($Vehicle_No, $vFromDate, $vToDate);
        $ArrCountR = count($mystrR);

        $mystrS=$DataSource->ArrayVehicleService($Vehicle_No, $vFromDate, $vToDate);
        $ArrCountS = count($mystrS);

        $Top=370;
        $Right=330;
        $LeftFront=32;
        $LeftBack=150;
        $footerline=810;		 
        $TotCost = 0;
        $TotACost =0;
        
        $pdf->ezText(Yii::app()->params['companyName'],14);
            $pdf->ezText('',2);
            $pdf->ezText(Yii::app()->params['sysName'],12);
            $pdf->ezText('',5);
            $pdf->ezText('Vehicle Repair & Service Detail Report - From:'.$vFromDate.' To:'.$vToDate,10);
            $pdf->ezText('',5);
            $pdf->ezText('Vehicle No. '.$Vehicle_No,10);
            $pdf->ezText('',28);		
            $pdf->addJpegFromFile("./images/NationalSymbol.jpg",'700','490','71','87');
//            $pdf->addText(650,480,8,"<i>'Towards Next Generation Government'</i>",0);	


            //--add Line to report
            $pdf->line(820,475,15,475);
            $pdf->line(820,473,15,473);
            $pdf->ezText('',15);
             //--set the table line style
            $pdf->setLineStyle(1);

            //--add Report footer 
            $pdf->line($footerline,20,15,20);
            $pdf->line(580,20,15,20);
            $pdf->addText(420,10,8,"Generated by- ".Yii::app()->getModule('user')->user()->username);	
            $Time = date("Y/m/d");
            $pdf->addText(640,10,8,$Time,0);					
            $pdf->ezStartPageNumbers(60,10,8);	
		
        if ($ArrCountR > 0 || $ArrCountS > 0 )  // $ArrCount start
        {
			
            			
		
            ##########################################################
            // Summary Information //

            $Total_Repair_Cost=Yii::app()->db->createCommand('SELECT SUM(Repair_Cost) AS "CostR" FROM vehicle_repair_details WHERE Vehicle_No= "'.$Vehicle_No.'"')->queryAll();
            $Total_Repair_Cost=$Total_Repair_Cost[0]['CostR'];

            $Total_Service_Cost=Yii::app()->db->createCommand('SELECT SUM(Estimate_Cost) AS "CostS",SUM(Other_Costs) AS "OtherCostS" FROM services WHERE Vehicle_No="'.$Vehicle_No.'"')->queryAll();		
            $Total_Service_Cost = $Total_Service_Cost[0]['CostS']+ $Total_Service_Cost[0]['OtherCostS'];	


            $Total_Repair_Cost_Date = Yii::app()->db->createCommand('SELECT SUM(Repair_Cost) AS "CostR" FROM vehicle_repair_details WHERE Vehicle_No= "'.$Vehicle_No.'" AND Repaired_Date BETWEEN "'.$vFromDate.'" AND "'.$vToDate.'" ')->queryAll();
            $Total_Repair_Cost_Date = $Total_Repair_Cost_Date[0]['CostR'];		

            $Total_Service_Cost_Date = Yii::app()->db->createCommand('SELECT SUM(Estimate_Cost) AS "CostS",SUM(Other_Costs) AS "OtherCostS" FROM services WHERE Vehicle_No= "'.$Vehicle_No.'" AND Service_Date BETWEEN "'.$vFromDate.'" AND "'.$vToDate.'" ')->queryAll();
            $Total_Service_Cost_Date = $Total_Service_Cost_Date[0]['CostS']+$Total_Service_Cost_Date[0]['OtherCostS'];
		
		
            $mystrSum=array( 
                array ( ' ' => 'From '.$vFromDate.' to '.$vToDate.' Cost', 'Repair'=> number_format($Total_Repair_Cost_Date,2), 'Service' => number_format($Total_Service_Cost_Date,2)),
                array ( ' ' => 'Previous Cost', 'Repair'=> number_format(($Total_Repair_Cost - $Total_Repair_Cost_Date),2), 'Service' => number_format($Total_Service_Cost-$Total_Service_Cost_Date,2)),
                array ( ' ' => '<b>Total', 'Repair'=> number_format($Total_Repair_Cost,2), 'Service' => number_format($Total_Service_Cost,2).'</b>')) ;

		
            if (count($mystrSum) > 0)
            {		
                $pdf->ezText("<b>Summary</b>",10);
                $pdf->ezText('',10);
                $pdf->ezTable($mystrSum,'','',array('xPos'=>'right','xOrientation'=>'left','width'=>720));
            }

            //--Detail information of Service & Repairs--

            if ($ArrCountR > 0)
            {
                $pdf->ezText('',20);
                $pdf->ezText("<b>Repair Details</b>",10);
                $pdf->ezText('',10);
                $pdf->ezTable($mystrR,'','',array('xPos'=>'right','xOrientation'=>'left','width'=>720));									
            }

            if ($ArrCountS > 0)
            {			
                $pdf->ezText('',20);
                $pdf->ezText('<b>Service Details</b>',10);
                $pdf->ezText('',10);			
                $pdf->ezTable($mystrS,'','',array('xPos'=>'right','xOrientation'=>'left','width'=>720));	
            }
                $pdf->ezStream();					
        }
        else
        {
            $pdf->ezText('* No data available for selected criteria',10);
            $pdf->ezStream();
        }
    }	
}

?>
