<?php

class vehicleBookingForm extends CFormModel
{

//public $Valid_From,$Valid_To;
	public $Valid_From;
	public $Valid_To;
	public $Booking_Status;

	
	
	public function rules()
	{
		return array(
			array('Valid_From, Valid_To, Booking_Status', 'required')
			
		);
	}
	
	 public function attributeLabels()
    {
        return array(
			'Valid_From'=>'From Date',	
			'Valid_To'=>'To Date',
			'Booking_Status'=>'Booking Status'		
		);
	}
	
	
	
	
    public function rprint($vFromDate,$vToDate,$bookingStatus)
	{
		$DataSource = new ReportDataSource;
		require_once('./protected/class/class.ezpdf.php');
		$pdf = new Cezpdf();
		$pdf->Cezpdf($paper='A4',$orientation='landscape');
      	$pdf->selectFont('./protected/class/fonts/Courier.afm');
      
		
		//--Get data array 
		$mystr=$DataSource->ArrayVehicleBooking($vFromDate,$vToDate, $bookingStatus);		
		$ArrCount = count($mystr);	
		
						
			//--add Heddings
		 //$pdf->ezText('Ministry of Public Administration and Home Affairs',19);
		 $pdf->ezText(Yii::app()->params['companyName'],14);
		 $pdf->ezText('',2);		
		 $pdf->ezText(Yii::app()->params['sysName'],12);
		 $pdf->ezText('',5);
		 $pdf->ezText('Vehicle Booking Report - Status wise',12);
		 $pdf->ezText('',5);		
	     $pdf->ezText('From: '.$vFromDate.' To: '.$vToDate,10);
		 if($bookingStatus !='All')
		 {
		    $pdf->ezText('Booking Status : '.$bookingStatus,10);
		 }
                $pdf->ezText('',28);		
                $pdf->addJpegFromFile("./images/NationalSymbol.jpg",'700','490','71','87');
                //$pdf->addText(650,480,8,"<i>'Towards Next Generation Government'</i>",0);
                $pdf->line(800,473,30,473);
                $pdf->line(800,475.5,30,475.5);
		//$pdf->ezStream();die;
		 $pdf->ezText('',10);
		 //--add Line to report
			 
		 
		 $tbwith=780;		 
		 $Top=690;
		 $Right=330;
		 $LeftFront=32;
		 $LeftBack=150;
		 
		// echo $ArrCount;exit;
		 
		 if ($ArrCount > 0)  // $ArrCount start
		{

			if($bookingStatus=='All')
			{
				$pdf->ezTable($mystr,array('username'=>'Requested By','Category_Name'=>'Category Name', 'Vehicle_No'=>'Vehicle No', 'Full_Name'=>'Driver Name','Description'=>'Reason','From'=>'From','To'=>'To','Booking_Status'=>'Booking Status', 'Mileage'=>'Distance'),'',array('xPos'=>'right','xOrientation'=>'left','width'=>$tbwith)); 
			}
			else
			{
				$pdf->ezTable($mystr,array('username'=>'Requested By', 'Category_Name'=>'Category Name','Vehicle_No'=>'Vehicle No', 'Full_Name'=>'Driver Name','Description'=>'Reason','From'=>'From','To'=>'To'),'',array('xPos'=>'right','xOrientation'=>'left','width'=>$tbwith)); 
			}
			
		 }
		else
		{
			$pdf->ezText('* No data available for selected criteria',10);
			$pdf->ezStream();
		}
		
		 $pdf->setColor(0.0,0.0,0.0);
		
			//--add Line to report (Page footer)---
			$pdf->line(820,20,15,20);
			$pdf->addText(420,10,8,"Generated by- ".Yii::app()->getModule('user')->user()->username);			
			$Time = date("Y/m/d");
			$pdf->addText(540,10,8,$Time,0);					
			$pdf->ezStartPageNumbers(60,10,8);					
			//---Footer End here----
				
			$pdf->ezStream();					
		
	}	
}

?>
