<?php

class vehicleAllocationForm extends CFormModel
{

	//public $Vehicle_No;
	public $Allocation_Type_ID;

	
	
	public function rules()
	{
		return array(
			array('Allocation_Type_ID', 'required')	
			
		);
	}
	
	public function attributeLabels()
    {
        return array(
			'Allocation_Type_ID'=>'Allocatin Type'			
		);                    
            
    }
	
	
	/*public function combodata($var)
	{
		
		if($var == 'DS')
		{
		   $values=	Yii::app()->db->createCommand()
                   ->select('DS_Division_ID, DS_Division_Name')
                   ->from('ma_ds_divisions')
					   /* ->join('tbl_profile p', 'u.id=p.user_id')
						->where('id=:id', array(':id'=>$id)) */ 
				   //->queryAll();
   			
		//}
		//elseif($var == 'GN')
		//{
		   	//$values=Yii::app()->db->createCommand()
                   //->select('GN_Division_ID, GN_Division_Name')
                   //->from('ma_gn_divisions')
                   //->queryAll();
				  
		//}
		//elseif($var == 'Member')
		//{
		   	//$values=Yii::app()->db->createCommand()
                   //->select('Member_ID, Name_with_Initials')
                   //->from('personal_details')
                   //->queryAll();
				  
		//}
		
		//return($values);
	//}*/
	
    public function rprint($vA_ID)
	{
		$DataSource = new ReportDataSource;
		require_once('./protected/class/class.ezpdf.php');
		$pdf = new Cezpdf();
		$pdf->selectFont('./protected/class/fonts/Courier.afm');
		
		//--Get data array 
		$mystr=$DataSource->ArrayVehicleAllocation($vA_ID);		
		$ArrCount = count($mystr);	
		
		$cri = new CDbCriteria();
        $cri->select ="Allocation_Type";
        $cri->condition="Allocation_Type_ID=$vA_ID";
        $arr = MaAllocationType::model()->findAll($cri);
        $allocationType='';
        if(count($arr)>0)
        {
            $allocationType = $arr[0]['Allocation_Type'];
        }
			//--add Heddings
		 //$pdf->ezText('Ministry of Public Administration and Home Affairs',19);
		 $pdf->ezText(Yii::app()->params['companyName'],14);
	
		 
		//$pdf->ezText('Local Governance Program',15);
		 $pdf->ezText('',2);
		 //$pdf->ezText('Fleet Management System',14);		
		 $pdf->ezText(Yii::app()->params['sysName'],12);
		 $pdf->ezText('',5);
		 $pdf->ezText('Vehicle Allocation Report',12);
		 $pdf->ezText('Type - '.$allocationType,10);
		 $pdf->ezText('',28);		
		 $pdf->addJpegFromFile("./images/NationalSymbol.jpg",'500','740','71','87');
		 //$pdf->addText(410,730,8,"<i>'Towards Next Generation Government'</i>",0);		
		
		 $pdf->ezText('',10);
		 //--add Line to report
		 $pdf->line(580,723,20,723);
		 $pdf->line(580,724.5,20,724.5);
		 //--set the table line style
		 //$pdf->setLineStyle(1);			 
		 //$pdf->line(580,20,15,20);		 
		 		 
		 $Top=690;
		 $Right=330;
		 $LeftFront=32;
		 $LeftBack=150;
		 
		
		 if ($ArrCount > 0)  // $ArrCount start
		{
			$pdf->ezTable($mystr,array('Vehicle_No'=>'Vehicle No.','Category_Name'=>'Category','Model'=>'Model', 'Make'=>'Make','Vehicle_Status'=>'Vehicle Status','Number_of_Passenger'=>'Passengers','Fitness_test'=>'Eligible for Fitness Test'),'',
			array('cols' => array('Number_of_Passenger'=>array('justification' => 'right')),'xPos'=>'right','xOrientation'=>'left','width'=>530));	
		}
		else
		{
			$pdf->ezText('* No data available for selected criteria',10);
			$pdf->ezStream();
		} 
		 
		 
		 
		 $pdf->setColor(0.0,0.0,0.0);
		
			//--add Line to report (Page footer)---
			$pdf->line(580,20,15,20);
			$pdf->addText(420,10,8,"Generated by- ".Yii::app()->getModule('user')->user()->username);			
			$Time = date("Y/m/d");
			$pdf->addText(540,10,8,$Time,0);					
			$pdf->ezStartPageNumbers(60,10,8);					
			//---Footer End here----
				
			$pdf->ezStream();					
		
	}	
}

?>
