<?php

class vehicleRepaireServiceForm extends CFormModel
{

	public $Vehicle_No;
	public $Vehicle_Category_ID;
	//public $Valid_From;
	//public $Valid_To;

	
	public function rules()
	{
		//return array(
			
		//);
		
		//return array(
//			array('Valid_From ,Valid_To', 'required')	
//			
//		);
	}
	
	 public function attributeLabels()
    {
        return array(
			'DS_Division_ID'=>'DS Division',
			'GN_Division_ID'=>'GN Division',
			'Member_ID'=>'Member',
			'Vehicle_No'=>'VehicleNo', //no need, if err occurs comment this
			'Vehicle_Category_ID'=>'Vehicle Category ID' //no need, if err occurs comment this
			
			
		
		);
                      
               
    }
	public function combodata($var)
	{
		
		if($var == 'DS')
		{
		   $values=	Yii::app()->db->createCommand()
                   ->select('DS_Division_ID, DS_Division_Name')
                   ->from('ma_ds_divisions')
					   /* ->join('tbl_profile p', 'u.id=p.user_id')
						->where('id=:id', array(':id'=>$id)) */ 
				   ->queryAll();
   			
		}
		elseif($var == 'GN')
		{
		   	$values=Yii::app()->db->createCommand()
                   ->select('GN_Division_ID, GN_Division_Name')
                   ->from('ma_gn_divisions')
                   ->queryAll();
				  
		}
		elseif($var == 'Member')
		{
		   	$values=Yii::app()->db->createCommand()
                   ->select('Member_ID, Name_with_Initials')
                   ->from('personal_details')
                   ->queryAll();
				  
		}
		
		return($values);
	}
	
    //public function rprint($Vehicle_No)
//	{
//		$DataSource = new ReportDataSource;
//		require_once('./protected/class/class.ezpdf.php');
//		$pdf = new Cezpdf();
//		$pdf->selectFont('./protected/class/fonts/Times-Roman.afm');
//		
//		//--Get data array 
//		$mystrR=$DataSource->ArrayVehicleRepaire($Vehicle_No);
//		//$mystrS=$DataSource->ArrayVehicleService($Vehicle_No);
//		$ArrCountR = count($mystrR);
//		
//		$mystrS=$DataSource->ArrayVehicleService($Vehicle_No);
//		//$mystrS=$DataSource->ArrayVehicleService($Vehicle_No);
//		$ArrCountS = count($mystrS);
//		
//		if ($ArrCountR > 0 || $ArrCountS > 0 )  // $ArrCount start
//		{				
//			//--add Heddings
//		 $pdf->ezText('Ministry of Public Administration and Home Affairs',19);
//		//$pdf->ezText('Local Governance Program',15);
//		 $pdf->ezText('',2);
//		 $pdf->ezText('Fleet Management System',14);		
//		 $pdf->ezText('',5);
//		 $pdf->ezText('Vehicle Repair/Service Detail Report ',12);
//		 $pdf->ezText('',5);
//		 $pdf->ezText('Vehicle No. '.$Vehicle_No,10);
//		 $pdf->ezText('',28);		
//		 $pdf->addJpegFromFile("./images/NationalSymbol.jpg",'500','740','71','87');
//		 $pdf->addText(436,730,8,"<i>''Towards Next Generation Government''</i>",0);		
//		
//		 //--add Line to report
//		 $pdf->line(560,723,30,723);
//		 $pdf->line(560,724.5,30,724.5);
//		 
//		 $pdf->addText(32, 690+7,14,"<b>Repair Details</b>",0);
//		 
//		 //$pdf->ezText('Repair Details',14);		
//		 $pdf->ezText('',5);
//		 //--set the table line style
//		 $pdf->setLineStyle(1);			 
//		 $pdf->line(580,20,15,20);	
//		 
//		
//		 		 
//		 //$Top=690;
//		 $Top=650;
//		 $Right=330;
//		 $LeftFront=32;
//		 $LeftBack=150;
//		 
//		 $TotCost = 0;
//		 $TotACost =0;
//		 
//		 for($a=0;$a<$ArrCountR;$a++)
//		 {
//		 
//		 $pdf->setColor(0.9,0.9,0.9);
//		 $pdf->filledRectangle(30, $Top,530,20);
//		 $pdf->setColor(0,0,0);
//		 $pdf->addText($LeftFront, $Top+7,10,"<b>Repairs Date</b>",0); //////// start
//		 $pdf->addText($LeftBack, $Top+7,10,"<i>" .$mystrR[$a]['Repairs_Date']."</i>",0);
//		 
//		 $pdf->addText($Right, $Top+7,10,"<b>Total Cost</b>",0);
//		 $pdf->addText($Right+120, $Top+7,10,"<i>" .$mystrR[$a]['Total_Cost']."</i>",0);
//		 
//		 
//		 $Top=$Top-20;
//		 $pdf->addText($LeftFront, $Top+7,10,"<b>Repairs Type</b>",0);
//		 $pdf->addText($LeftBack, $Top+7,10,"<i>" .$mystrR[$a]['Repairs_Type']."</i>",0);
//		 		 
//		 
//		 $pdf->addText($Right, $Top+7,10,"<b>Garage Name</b>",0);
//     	 $pdf->addText($Right+120, $Top+7,10,"<i>" .$mystrR[$a]['Garage_Name']."</i>",0);
//		 
//		 //$Top=$Top-20;
////		 $pdf->setColor(0.9,0.9,0.9);
////		 $pdf->filledRectangle(30,$Top,530,20);
////		 $pdf->setColor(0,0,0);
////		 $pdf->addText($LeftFront, $Top+7,10,"<b>Repairs Type</b>",0);
////		 $pdf->addText($LeftBack, $Top+7,10,"<i>" .$mystrR[$a]['Repairs_Type']."</i>",0);
////		 
//		
//    	 //$pdf->addText($Right, $Top+7,10,"<b></b>",0);
//     	 //$pdf->addText($Right+120, $Top+7,10,"<i>" .$mystr[0]['']."</i>",0);
//		 
//		 //$pdf->setColor(0.0,0.0,0.0);
//		 $TotCost += $mystrR[$a]['Total_Cost'];
//		 $Top=$Top-40;
//		 //$pdf->setColor(0.9,0.9,0.9);
//		 //$pdf->filledRectangle(30,$Top,530,20);
//		 //$pdf->setColor(0,0,0);
//		 //$pdf->addText($LeftFront, $Top+7,10,"<b>Repairs Type</b>",0);
//		 if ($Top <=0)
//		 {
//		 	$Top = 750;
//			$pdf->line(580,20,15,20);
//			 $pdf->addText(420,10,8,"Generated by- ".Yii::app()->getModule('user')->user()->username);			
//			$Time = date("Y/m/d");
//			$pdf->addText(540,10,8,$Time,0);					
//			$pdf->ezStartPageNumbers(60,10,8);	
//			
//			$pdf->ezNewPage();
//		 }
//			
//			
//		 
//		 }
//		 
//		$Top=$Top-5;
//		 if ($Top <=0)
//		 {
//		 	$Top = 750;
//			$pdf->line(580,20,15,20);
//			 $pdf->addText(420,10,8,"Generated by- ".Yii::app()->getModule('user')->user()->username);			
//			$Time = date("Y/m/d");
//			$pdf->addText(540,10,8,$Time,0);					
//			$pdf->ezStartPageNumbers(60,10,8);	
//			
//			$pdf->ezNewPage();
//		 }
//		
//		$pdf->line(560,$Top+40,30,$Top+40);
//		$pdf->addText($Right+80, $Top+25,12,"<b>Total Cost: Rs. ".$TotCost."</b>",0);
//		$pdf->line(560,$Top+20,30,$Top+20);
//		
//		 
//		if ($ArrCountS > 0)  // $ArrCount start
//		{			
//		 
//		 $Top=$Top-10;
//		 $pdf->addText($LeftFront, $Top+7,14,"<b>Service Details</b>",0);
//		 
//		 $Top=$Top-40;
//		
//		 
//		 for($a=0;$a<$ArrCountS;$a++)
//		 {
//		 
//		 $pdf->setColor(0.9,0.9,0.9);
//		 $pdf->filledRectangle(30, $Top,530,20);
//		 $pdf->setColor(0,0,0);
//		 $pdf->addText($LeftFront, $Top+7,10,"<b>Service Date</b>",0); //////// start
//		 $pdf->addText($LeftBack, $Top+7,10,"<i>" .$mystrS[$a]['Service_Date']."</i>",0);
//		 
//		 $pdf->addText($Right, $Top+7,10,"<b>Service Station</b>",0);
//		 $pdf->addText($Right+120, $Top+7,10,"<i>" .$mystrS[$a]['Srvice_Station_Name']."</i>",0);
//		 
//		 
//		 $Top=$Top-20;
//		 $pdf->addText($LeftFront, $Top+7,10,"<b>Service Type</b>",0);
//		 $pdf->addText($LeftBack, $Top+7,10,"<i>" .$mystrS[$a]['Service_Type']."</i>",0);
//		 		 
//		 
//		 $pdf->addText($Right, $Top+7,10,"<b>Meter Reading</b>",0);
//     	 $pdf->addText($Right+120, $Top+7,10,"<i>" .$mystrS[$a]['Meter_Reading']."</i>",0);
//		 
//		 $Top=$Top-20;
//		 $pdf->setColor(0.9,0.9,0.9);
//		 $pdf->filledRectangle(30,$Top,530,20);
//		 $pdf->setColor(0,0,0);
//		 $pdf->addText($LeftFront, $Top+7,10,"<b>Next Service Date</b>",0);
//		 $pdf->addText($LeftBack, $Top+7,10,"<i>" .$mystrS[$a]['Next_Service_Date']."</i>",0);
//		 
//		
//    	 $pdf->addText($Right, $Top+7,10,"<b>Next Service Milage</b>",0);
//     	 $pdf->addText($Right+120, $Top+7,10,"<i>".$mystrS[0]['Next_Service_Milage']."</i>",0);
//		 
//		  $Top=$Top-20;
//		 $pdf->addText($LeftFront, $Top+7,10,"<b>Driving Distance</b>",0);
//		 $pdf->addText($LeftBack, $Top+7,10,"<i>" .$mystrS[$a]['Driving_Distance']."</i>",0);
//		 		 
//		 
//		 $pdf->addText($Right, $Top+7,10,"<b>Description</b>",0);
//     	 $pdf->addText($Right+120, $Top+7,10,"<i>" .$mystrS[$a]['Description']."</i>",0);
//		 
//		 $Top=$Top-20;
//		 $pdf->setColor(0.9,0.9,0.9);
//		 $pdf->filledRectangle(30,$Top,530,20);
//		 $pdf->setColor(0,0,0);
//		 $pdf->addText($LeftFront, $Top+7,10,"<b>Estimate Cost</b>",0);
//		 $pdf->addText($LeftBack, $Top+7,10,"<i>" .$mystrS[$a]['Estimate_Cost']."</i>",0);
//		 
//		
//    	 $pdf->addText($Right, $Top+7,10,"<b>Service Replacement</b>",0);
//     	 $pdf->addText($Right+120, $Top+7,10,"<i>".$mystrS[0]['Service_Replacement']."</i>",0);
//		 
//		 $TotACost += $mystrS[$a]['Estimate_Cost'];
//		 $Top=$Top-40;
//		 //$pdf->setColor(0.9,0.9,0.9);
//		 //$pdf->filledRectangle(30,$Top,530,20);
//		 //$pdf->setColor(0,0,0);
//		 //$pdf->addText($LeftFront, $Top+7,10,"<b>Repairs Type</b>",0);
//		 if ($Top <=0)
//		 {
//		 	$Top = 750;
//			$pdf->line(580,20,15,20);
//			 $pdf->addText(420,10,8,"Generated by- ".Yii::app()->getModule('user')->user()->username);			
//			$Time = date("Y/m/d");
//			$pdf->addText(540,10,8,$Time,0);					
//			$pdf->ezStartPageNumbers(60,10,8);	
//			
//			$pdf->ezNewPage();
//		 }
//		 
//		 }
//		
//		 $Top=$Top-5;
//		 //$pdf->ezNewPage();
//		  if ($Top <=0)
//		 {
//		 	$Top = 750;
//			$pdf->line(580,20,15,20);
//			 $pdf->addText(420,10,8,"Generated by- ".Yii::app()->getModule('user')->user()->username);			
//			$Time = date("Y/m/d");
//			$pdf->addText(540,10,8,$Time,0);					
//			$pdf->ezStartPageNumbers(60,10,8);	
//			
//			$pdf->ezNewPage();
//			
//			
//			
//		 }
//		$pdf->line(560,$Top+40,30,$Top+40);
//		$pdf->addText($Right+40, $Top+25,12,"<b>Total Estimate Cost: Rs. ".$TotACost."</b>",0);
//		$pdf->line(560,$Top+20,30,$Top+20);
//		 
//	}
//		 
//		 //$pdf->ezText('Service Details',14);		
//		// $pdf->ezText('',5);
//		
//			//--add Line to report (Page footer)---
//			$pdf->line(580,20,15,20);
//			 $pdf->addText(420,10,8,"Generated by- ".Yii::app()->getModule('user')->user()->username);			
//			$Time = date("Y/m/d");
//			$pdf->addText(540,10,8,$Time,0);					
//			$pdf->ezStartPageNumbers(60,10,8);					
//			//---Footer End here----
//				
//			$pdf->ezStream();					
//		}
//		else
//		{
//			//if ($ArrCountS == 0)
//			//{
//			$pdf->ezText('* No data available for selected criteria',10);
//			$pdf->ezStream();
//			//}
//		}
//	}	
}

?>
